{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - {{- if .Values.httpRoute.matches }}
      matches:
        {{- toYaml .Values.httpRoute.matches | nindent 8 }}
      {{- end }}
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            remove:
              - X-Powered-By
      backendRefs:
        - name: {{ include "charts.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
